In [2]:
import torch_scatter
import torch
from torch_geometric.utils import to_dense_adj, dense_to_sparse

In [3]:

A= torch.Tensor([[1, 0, 1, 1], [0, 1, 1, 1], [1, 1, 0, 1], [1, 0, 0, 1]])
print("number of edges=", A.sum())
edge_index, edge_weight= dense_to_sparse(A)
row, col= edge_index
out_deg = torch_scatter.scatter_add(edge_weight, row, dim=0)
in_deg  = torch_scatter.scatter_add(edge_weight, col, dim=0)
print(f"out_deg={out_deg}")
print(f"in_deg={in_deg}")
print(A.sum(dim=0))
print(A.sum(dim=1))

number of edges= tensor(11.)
out_deg=tensor([3., 3., 3., 2.])
in_deg=tensor([3., 2., 2., 4.])
tensor([3., 2., 2., 4.])
tensor([3., 3., 3., 2.])


In [4]:
A= torch.Tensor([[1, 0, 0], [0, 0, 1], [0, 0, 0]])
edge_index, edge_weight= dense_to_sparse(A)
print(f"edge_weight={edge_weight}")
row, col= edge_index
print(f"row={row}")
print(f"col={col}")
out_deg = torch_scatter.scatter_add(edge_weight, row, dim=0 )
in_deg  = torch_scatter.scatter_add(edge_weight, col, dim=0)
print(f"out_deg={out_deg}")
print(f"in_deg={in_deg}")
print(A.sum(dim=0))
print(A.sum(dim=1))

edge_weight=tensor([1., 1.])
row=tensor([0, 1])
col=tensor([0, 2])
out_deg=tensor([1., 1.])
in_deg=tensor([1., 0., 1.])
tensor([1., 0., 1.])
tensor([1., 1., 0.])


In [5]:
out_deg.numpy()

array([1., 1.], dtype=float32)

In [6]:
A= torch.Tensor([[1, 0, 0], [0, 0, 1], [0, 0, 0]])
print("number of edges=", A.sum())

edge_index, edge_weight= dense_to_sparse(A)
row, col= edge_index

out_deg = torch_scatter.scatter_add(edge_weight, row,  dim_size=A.size(0))

in_deg  = torch_scatter.scatter_add(edge_weight, col,  dim_size=A.size(0))
print(f"out_deg={out_deg}")
print(f"in_deg={in_deg}")
print(A.sum(dim=0))
print(A.sum(dim=1))

number of edges= tensor(2.)
out_deg=tensor([1., 1., 0.])
in_deg=tensor([1., 0., 1.])
tensor([1., 0., 1.])
tensor([1., 1., 0.])


In [10]:
edge_weight

tensor([1., 1.])